repos:
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v2.0.2'  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8

-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
